old_file = open("연락처.txt", "rt")
buffer = old_file.read()
n = buffer.count("011-")
buffer.replace("011-", "010-")
print("총 {}건의 011 데이터를 찾았습니다".format(n))
old_file.close()

new_file = open("연락처.txt", "wt")
new_file.write(buffer)
new_file.close()
print("데이터 수정 완료!")